input {
    # http 5044번 입력
    http {
        port => 5044
        codec => json
    }
}

filter {
    # Grok이라는 도구를 이용하여 비정형 데이터 => 반정형 데이터 변환 처리
    if [log] {
        grok {
            match => { "log" => "\[%{TIMESTAMP_ISO8601:timestamp}\] ID=%{DATA:sensor_id} \|\s+TEMP:%{NUMBER:temperature:float} \|\s+HUMI:%{NUMBER:humidity:float} \|\s+STAT:%{WORD:status}" }
        }
        mutate {
            remove_field => [ "headers", "host", "@version", "event", "http", "log" ]
        }
    } else if [message] {
        grok {
            match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] ID=%{DATA:sensor_id} \|\s+TEMP:%{NUMBER:temperature:float} \|\s+HUMI:%{NUMBER:humidity:float} \|\s+STAT:%{WORD:status}" }
        }
        mutate {
            remove_field => [ "headers", "host", "@version", "event", "http", "message" ]
        }
    }
}

output {
    # Kafka 브로커 전달 (9092)
    kafka {
        bootstrap_servers => "kafka:9092"
        topic_id => "factory-text-topic"
        codec => json
    }
    stdout {
        codec => rubydebug
    }
}